// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<bool> checkAccessibilityPermission() =>
    RustLib.instance.api.crateApiCheckAccessibilityPermission();

Future<void> requestAccessibilityPermission() =>
    RustLib.instance.api.crateApiRequestAccessibilityPermission();

Future<bool> checkScreenRecordingPermission() =>
    RustLib.instance.api.crateApiCheckScreenRecordingPermission();

Future<void> requestScreenRecordingPermission() =>
    RustLib.instance.api.crateApiRequestScreenRecordingPermission();

Future<bool> checkFullDiskAccessPermission() =>
    RustLib.instance.api.crateApiCheckFullDiskAccessPermission();

Future<void> requestFullDiskAccessPermission() =>
    RustLib.instance.api.crateApiRequestFullDiskAccessPermission();

Future<bool> checkWindowsAdmin() =>
    RustLib.instance.api.crateApiCheckWindowsAdmin();

Future<void> requestWindowsAdmin() =>
    RustLib.instance.api.crateApiRequestWindowsAdmin();
